apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo

spec:
  volumes:
    - name: shared-data
      emptyDir: {}

  containers:
    - name: writer
      image: busybox
      command:
        - sh
        - -c
        - |
          while true
          do
            date > /shared/time.txt
            sleep 2
          done

      volumeMounts:
        - name: shared-data
          mountPath: /shared

    - name: reader
      image: busybox
      command:
        - sh
        - -c
        - |
          while true
          do
            cat /shared/time.txt
            sleep 2
          done

      volumeMounts:
        - name: shared-data
          mountPath: /shared
