services:
  service-a:
    build:
      context: ./service-a
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    depends_on:
      - service-b
    environment:
      - TAX_SERVICE_URL=http://service-b:4000

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    ports:
      - "3200:4000"

  frontend:
    