name: Second CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: second CI
        run: echo "This is the second CI workflow"

      - name: ENV_VALUE
        run: echo "ENV_VALUE is ${{ secrets.ENV_VALUE }}"

      - name: DB_PASSWORD
        run: echo "DB_PASSWORD is ${{ secrets.DB_PASSWORD }}"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: TEstJob
        run: echo "This is the test job in the second CI workflow"
