apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-a
depends on:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-a
  template:
    metadata:
      labels:
        app: deployment-a
    spec:
      containers:
        - name: deployment-a
          image: nginx
          resources: {}
