apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-c
spec:
  selector:
    matchLabels:
      app: deployment-c
  template:
    metadata:
      labels:
        app: deployment-c
    spec:
      containers:
        - name: deployment-c
          image: nginx
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"
